### PR TITLE
Allow a combobox to have a wider popup

### PR DESCRIPTION
**Pull request by daWoife**
In some cases you can't allow a comboxbox to be its preferred size, because it wants to be as wide as the widest entry it has. As an example think about three comboboxes in a row, postal code, city and country.
You can not let the country combobox have it's preferred size, because it would be too wide only for a few countries with long names.  
WebComboBoxUI currently sets the wide of the popup exactly to the wide of the comboxbox.
With this change you can deside if the popup is allowed to be wide enouth to fit all its entries or not.

combobox

### CODE REVIEW

**Comment by mgarin** [comment]
This is actually a good improvement, thanks! :)
I will merge it a bit later today and will also add a bridge method into WebComboBox to setup this option.

**Comment by daWoife** [comment]
Hi Mikle, thanks. :-)

**Comment by mgarin** [comment]
Thanks for the checkbox position fix, that is a really neat one! :)

About combobox - I will be adding some improvements over your changes to add some more options for popup behavior. Most likely it will be an enum with various options how popup should be displayed (fit, extend to right, extend to left) and whether it can have width smaller than the combobox has.

**Comment by daWoife** [comment]
Hi, thanks. :-)
Yes would be cool to have all these choices.

**Comment by Sciss** [comment]
How are you guys feeling about the border style of CheckBox? I find the blurriness quite confusing, given that no single other widget has this kind of border. What was the reason not use the thinner and sharper style used by the other widgets (e.g. TextField, ComboBox)? To me the current look implies either a glitch or the impression that the check-box has a focus ring or something.

**Pull request merged**
