### PR TITLE
Update RSyntaxTextArea to version 2.5.8

### PR DESCRIPTION
**Pull request by iMichka**
The .jar file is coming from here:
http://search.maven.org/#search%7Cga%7C1%7Crsyntaxtextarea%20jar
You may double check the md5 sum.

Also, I saw that you are adding maven support. I do not know if you plan to build the weblaf-complete target through maven, but this may be a good thing so you can remove the .jars from the lib folder and let maven download them for you.

### CODE REVIEW

**Comment by mgarin** [comment]
Thanks for the update, I will merge this slightly later since ANT build and property file changes are also required not to break the build script.

> Also, I saw that you are adding maven support. I do not know if you plan to build the weblaf-complete target through maven, but this may be a good thing so you can remove the .jars from the lib folder and let maven download them for you.

Only `core`, `ui` and `demo` module artifacts will be released to maven. I don't think it's a good idea to upload `complete` artifact there as it kind of goes against maven ideology. I will simply upload `complete` artifact with releases - to the site and GitHub, and snapshot updates - to the site only.

If you are using maven you don't need `complete` artifact anyway, simply use the `weblaf-ui` one which will be sufficient to build an application or `weblaf-core` if you only need some base features offerred by the library.

Later on there will be more modules within the library and each separate module will also have its own artifact - you can read my thoughts/plans about that in issue #336

**Comment by iMichka** [comment]
Thanks. You are right, pushing the ```weblaf-complete``` artifact to maven does not make sense.

I will use the ```weblaf-ui``` artifact. I previously used the ```weblaf-complete``` artifact because it was faster to implement in our home-made build/release system, as the dependencies were already delivered with it. But this has proven problematic lately.

**Comment by mgarin** [comment]
> it was faster to implement in our home-made build/release system, as the dependencies were already delivered with it

Before WebLaF was released into Maven that was certainly true, however now all dependencies are also delivered with `weblaf-ui` module so it should also work for you if you are using Maven :)

I have merged the updated library, thanks again!

**Comment by mgarin** [comment]
I have also pushed updated sources - `rsyntaxtextarea-2.5.8-sources.jar`

**Pull request merged**
