### PR TITLE
Extended popup behavior for combobox

### PR DESCRIPTION
**Pull request by daWoife**
For a combobox it can be nice to have the opportunity to hide or to disable the button for the popup.
This can be useful for a input history list for example, so if you have no input history, you only see a normal input field. If you have a input history, you see a combobox with a dropdown list. 
Or you always see a combobox, but the button is disabled if no history is available und the popup would be empty. 

With this request you have four more methods in WebComboBoxUI to control this behavior
(isButtonEnabled, setButtonEnabled, isButtonVisible, setButtonVisible).

### CODE REVIEW

**Comment by mgarin** [comment]
For some weird reason I don't see any changes provided by this particular pull request. Did something get lost or I've managed to add the same changes into master before somehow?

**Comment by mgarin** [comment]
Also I would really like to keep master branch intact at this point and to direct all changes into `styling` branch, if it is possible.

**Comment by daWoife** [comment]
Hi Mikle,
sorry I simple was too stupid to do it the right way. Long time ago I did something on github.
So I did the pull request before the file commit. :-)
Now we have a commit for the file WebComboBoxUI in my branch with the changes.
Can you see that and should I make an new pull request ?

**Comment by mgarin** [comment]
No problem, I'll check the new pull request :)

**Pull request closed without merging**
