### PR TITLE
Adds a WebTableStyle option to always show the right header border.

### PR DESCRIPTION
**Pull request by phxql**
Hello,

this adds a WebTableStyle option to always show the right header border.

### CODE REVIEW

**Comment by mgarin** [comment]
Thanks for the changes!
I will include those into final v1.29 release.

**Comment by mgarin** [comment]
I went through the code once more and I'm not sure what exactly was the reason for this change, could you clarify this a bit? Existing right side header border painting conditions should be sufficient.

**Comment by mgarin** [comment]
I'll move this change to v1.3.0 update, at least until the case is clarified.

**Comment by phxql** [comment]
We had a table, which was as big as the screen. Inside the table were three columns. Every column has a white seperator line, except the last one. Problem is: if the last column isn't as wide as the right border of the whole table, the text in the table is truncated, but the user doesn't recognize that the column isn't as wide as the table. And that's because the last column doesn't get a separator.

**Comment by mgarin** [comment]
@phxql Thanks for explanation! That does indeed clarify the case :)

As I understand you are talking about table with auto resize mode set to `JTable.AUTO_RESIZE_OFF`, right? In that case last header and column border is indeed not displayed and that might cause inconvenience since because doesn't actually use the whole table width, but it looks like it does

The border was supposed to disappear only in cases when table is set to auto resize mode since drawing it would be meaningless (columns always fill up the whole table width).

I will make adjustments to the painting code to make sure those borders are properly displayed when needed and hidden when they are not.

**Comment by mgarin** [comment]
Fix for this issue will be added in v1.29 update.

**Comment by mgarin** [comment]
Fix for this problem is available in the `styling` branch code and any snapshot build.
It will also be included in the final v1.2.9 update.

**Pull request closed without merging**
