### PR TITLE
Allow to set background color of internal frames

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by mgarin** [comment]
Just a few notes about additions similar to this one:

- Adding a bridge method into Web* component would also be nice. For example if you add some field `backgroundColor` - there should be getter/setter methods in *UI class and Web* class - for example in `WebInternalFrameUI` and `WebInternalFrame`. Otherwise some other future features depending on those setters would be in a mess.

- *Style classes with style constants should be placed near the UI class, not in the skin package. These style classes are mostly a temporary measure to allow global styles modification, those will be completely replaced with StyleManager in the end.

**Comment by mgarin** [comment]
I have added minor changes based on notes above.

**Comment by iMichka** [comment]
Thanks for the explanations. I was not always sure where to put stuff. I am aware this changes (and the other ones I made) are somewhat temporary solutions as the StyleManager will be replacing those in the future.

* 1 I'll try to do this when needed.

* 2 I realized after your comment that I was overriding the setters and getters from JInternalFrame. The ones I added were not needed.

* 3 I don't remember why I put the Style class there. I think maybe I found one or two other Style classes there so I thought it would be safe to put it here. Of course it's much better in the folder you moved the file in.

Thanks for the code review and the fixes.

**Comment by mgarin** [comment]
In any case - don't worry, I am still expecting all the code to ensure that other stuff is not affected by the changes (that might happens since there are a lot of tricky code around). 

And you have actually followed the base guideline I have put for myself pretty nicely even without knowing how/where stuff should be placed :)

About notes:

1. It might be needed if that is some new, for example some setting which wasn't using a separate field yet. Still it pretty case-specific.
2. Basically yes, but it is still handy to have default background in a style class instead of "shady" global defaults table which cannot be read easly.
3. Probably you've seen the *PainterStyle classes there - those are default settings for painters which are totally different :)

And no problem, will keep merging stuff in.

**Pull request merged**
