### PR TITLE
Allow to set progressbar border color

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by daWoife** [comment]
I really don't understand how someone can think his name should be added as author in existing moduls of somebody else's big software project for simply providing some setter and getter methods.

**Comment by iMichka** [comment]
Hi

ho that. I did it just because @mgarin has asked me to do so (and he added once or two my name to previous PR's). I don't really care, I can also remove my name.

P.S. no code change is trivial. You need to understand the code first, modify it, test it, and make a PR. Adding these getters/setters is taking roughly 20 minutes, even if it is a few lines.

**Comment by daWoife** [comment]
Of course it is trival to provide some setter or getter methods for a class if you have only little programming experience. :-) 
You even dit it wrong, the convention would be to name the methods getProgressEnabledBorderColor, setProgressEnabledBorderColor, etc.
But of course it's ok if mikle really told you to do that. But I never saw it before from other people making PRs here, and so I couldn't resist to mention it yesterday.

**Comment by iMichka** [comment]
Oups that was a typo, I updated the getP/setP names. Thanks for the note. I'm coming from the Python world, were you barely ever write getter/setters. So adapting to Java is sort of ... confusing ... :)

I also removed my name, I think it's more reasonable. Each community has different ways of doing this so I just did what mikle told, thinking no harm in doing so.

**Comment by daWoife** [comment]
Ok. :-)

**Comment by mgarin** [comment]
@iMichka 
Thanks for the changes!
Was away for a week and couldn't merge changes earlier.

> I really don't understand how someone can think his name should be added as author in existing moduls of somebody else's big software project for simply providing some setter and getter methods.

Well, I indeed asked for that since otherwise it looks like I did all the changes/improvements even if some of those are provided by other developers. And in my opinion even a small change deserves to be noted and `@author` mark is the least thing that could be done there.

It is up to you though - whether you want to add it or not. I don't insist that much, that was basically a suggestion. I know that some people like to leave their autographs and some don't like to do that at all, so if you don't want it to be there just ignore what I said :)

> P.S. no code change is trivial. You need to understand the code first, modify it, test it, and make a PR. Adding these getters/setters is taking roughly 20 minutes, even if it is a few lines.

And this as well. To change even a small portion of code in most cases you have to read (at least) all surrounding code to avoid producing additional issues.

For example even getters/setters can be tricky if library uses some reflection to access stuff like WebLaF does, and a lot actually in the styling code part.

**Pull request merged**
