### PR TITLE
JPopupMenu: eliminate flickering of translucent/shaped heavyweight popups on Linux

### PR DESCRIPTION
**Pull request by greg2001**
This should eliminate (or, at least minimize) flickering described in https://github.com/mgarin/weblaf/pull/268 and, maybe, https://github.com/mgarin/weblaf/issues/158

### CODE REVIEW

**Comment by mgarin** [comment]
Good point, this should indeed help.
Thanks for the changes!

I will also add those into `styling` branch.

**Comment by mgarin** [comment]
Though now I have found an issue on Windows with this way of installing transparency - popup menu shows up only once and then disappears forever. Without the old code it always works like that. I will probably leave both - old and new parts there, it seems to be working smoothly.

**Comment by greg2001** [comment]
Sorry for breaking things, I'll re-check that. The best way would probable be to attach a ComponentListener to the heavyweight window and setup transparency in componentShown() or componentResized(), but these windows are cached and shared between multiple popups so the listener has to be removed after the popup was hidden. Too much stuff for a simple thing - that's why I tried to avoid the listener. The whole popup handling in Swing is just a large piece of junk...

**Comment by greg2001** [comment]
Hi Mickle,

would you provide me with more info on how to reproduce the bug you're talking about, an SSCCE or something like that?
Tried to reproduce it with our application - no luck.

Thank you
Gregory

**Comment by mgarin** [comment]
Since I didn't add any changes in the `master` branch yet, issue be reproduced using its latest revision under Windows 7 or 8. It is enough to add a button and popup menu that will be displayed under that button:
```java
public final class MenuExample
{
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();

        final WebButton button = new WebButton ( "Show menu", new ActionListener ()
        {
            @Override
            public void actionPerformed ( final ActionEvent e )
            {
                final WebPopupMenu menu = new WebPopupMenu ();
                menu.add ( new WebMenuItem ( "Item 1" ) );
                menu.add ( new WebMenuItem ( "Item 2" ) );
                menu.add ( new WebMenuItem ( "Item 3" ) );
                menu.showBelowMiddle ( ( Component ) e.getSource () );
            }
        } );

        TestFrame.show ( button, 50 );
    }
}
```
It doesn't even matter if you will re-create this menu or keep it - it won't appear more than once. Since popup menu is used in different places like combobox the issue appears there as well:
```java
public final class ComboBoxExample
{
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();

        final WebComboBox box = new WebComboBox ( new String[]{ "Item 1", "Item 2", "Item 3" } );

        TestFrame.show ( box, 50 );
    }
}
```
I actually had that issue long ago in later JDK versions though it appeared under different conditions. I tried a lot of variations and had to add the workaround that was there till these changes (the one provided in listener that re-applied settings each time window is made visible).

Anyway, I have already patched up the code in `styling` branch, so it will be available in `master` branch later on. I combined your fix (which indeed fixes the flickering on systems where it is visible) with some of my old workarounds and made it more clear since it was actually pretty outdated and even had a few unreachable blocks. I have tested it under Ubuntu 14 / Win 7 & 8 / Mac OS X with different JDKs and it works fine on each of those setups, so I assume it will be working properly with the branch changes. Probably some issues will still appear on some specific configurations, will see that after the update.

**Comment by mgarin** [comment]
You might also want to try out examples provided above on your OS to see if it works well or old issues have returned. Branch `styling` can be found here: https://github.com/mgarin/weblaf/tree/styling

**Comment by greg2001** [comment]
Was able to reproduce this issue with Java 6/7, but not with Java 8 anymore, so that it's most likely an (already fixed) Java bug. Good to hear that you've found a workaround for that.

Thank you
Gregory

**Pull request merged**
