### PR TITLE
file-chooser improvements

### PR DESCRIPTION
**Pull request by Sciss**
483b81a : styles replace hard-coded colors in file-list renderer; name, description and size colors can be specified in the XML now.
ec90de1 : hot-keys for file-chooser view types (control-1, 2, 3); 9ac5e6f fixes a problem with focus loss 
8cbf58f : fix wong cell renderer and style warning in WebFileChooserPanel - history list
6d6aae5 and  33649e8 : allow to sub-class WebFileChooserUI and extends the chooser-panel

### CODE REVIEW

**Comment by Sciss** [comment]
Hello Mikle. Any thoughts or objections to this?

**Comment by mgarin** [comment]
- `WebFileListCellRenderer` & `filelist.xml` changes seem to be reasonable, no objections there :)

- Changes to `WebFileChooser` aren't reasonable due to the way all web-components should work. Did you have any specific reason to replace `updateUI` method code with super call?

- About `WebFileChooserPanel` changes - not sure that `1` `2` and `3` hotkeys are the best for view change. These hotkeys would cause the view to switch when you might simply want to quick-search through list/table by the file name containing those numbers. I'd rather go for something less accessible like `Ctrl+1` hotkey.

- `WebFileChooserUI` changes - no objections, that makes default implementation more customizeable.

- `WebScrollPaneCorner` changes - no objections, but this class will soon be removed (as well as similar classes for table, toolbar and some other places) and replaced with new component `WebCanvas` that will provide a simple empty component with painters/decorations support.

- `WebScrollPaneUI` & `scrollpane.xml` - as I understand those changes simply follow `WebScrollPaneCorner` changes, so that code will become meaningless with addition of `WebCanvas`. Also in general - it is better not to add any custom settings in painters that are fully based on decorations as it would limit your decoration options.

- `slider.xml` - seems reasonable, no objections.

**Comment by Sciss** [comment]
> Changes to WebFileChooser aren't reasonable due to the way all web-components should work. Did you have any specific reason to replace updateUI method code with super call?

Yes, I need to install a sub-class of `WebFileChooserUI` (33649e8aeee0adec05de2572d2b9c57241dbbc92) that in turn installs sub-class `WebFileChooserPanel` (6d6aae5bbb381ecfcc8b33c75839a3ecb763a407), because I am populating roots list differently. The problem with the original code:

    setUI ( ( WebFileChooserUI ) ReflectUtils.createInstance ( WebLookAndFeel.fileChooserUI ) );

This hard-codes the UI class and disables the possibility to create a derived LaF. If you look into what the `super` does, it is essentially the same you are doing, except that it takes the class name via defaults. So. `UIManager.getUI(this)` ends up doing the same as you are doing, using reflection to instantate the UI and calling static `createUI`, except that it allows us to install a sub-class.

> About WebFileChooserPanel changes - not sure that 1 2 and 3 hotkeys are the best for view change. ... I'd rather go for something less accessible like Ctrl+1 hotkey.

That's exactly what I did! (Meta-1/2/3 on Mac and Ctrl-1/2/3 on Windows and Linux).

> WebScrollPaneUI & scrollpane.xml - as I understand those changes simply follow WebScrollPaneCorner changes, so that code will become meaningless with addition of WebCanvas

Perhaps, but it would be good to have a work-around in the meantime.

**Comment by Sciss** [comment]
On second thought, 33649e8aeee0adec05de2572d2b9c57241dbbc92 might be less relevant, as I encounter this problem only with the style-editor that hard-codes the component sub-class `WebFileChooser`. In the real application I'm going straight for `JFileChooser` so that is not affected, if I'm not mistaken.

(that implies in general that overriding `updateUI` is not very good because it will miss the case where you don't use component sub-classes)

**Comment by mgarin** [comment]
> Yes, I need to install a sub-class of WebFileChooserUI (33649e8) that in turn installs sub-class WebFileChooserPanel (6d6aae5), because I am populating roots list differently. The problem with the original code:

> ```
setUI ( ( WebFileChooserUI ) ReflectUtils.createInstance ( WebLookAndFeel.fileChooserUI ) );
```

> This hard-codes the UI class and disables the possibility to create a derived LaF. 

Hm, not really - you can provide your UI into the `WebLookAndFeel.fileChooserUI` field. 
All static fields in `WebLookAndFeel` referencing UI class names are not final.

Though I would agree that modifying L&F class fields is a pretty bad way to provide customized UI classes. Also there is a minor issue with initialization order that might cause `StyleableComponent` to use the wrong default UI class causing XML style parser to be limited to default UI class fields. But I will make sure to fix this soon and provide convenient way to setup custom UIs into L&F.

> If you look into what the super does, it is essentially the same you are doing, except that it takes the class name via defaults. So. UIManager.getUI(this) ends up doing the same as you are doing, using reflection to instantate the UI and calling static createUI, except that it allows us to install a sub-class.

The whole point of the `updateUI` method override is to force `Web*` UIs usage, at least as base for any custom UIs. That is a pretty strict limitation but it shouldn't cause any issues. The point with this limitation is that I could then provide some general guidelines for the corresponding UIs developer of the custom UI will have to follow.

> That's exactly what I did! (Meta-1/2/3 on Mac and Ctrl-1/2/3 on Windows and Linux).

Yep, sorry for that one, I totally missed the mask definition there. It looks good :)

> Perhaps, but it would be good to have a work-around in the meantime.

The change will hit pretty soon (right after the changes I will push today) because that whole part with the scroll corners is really messy right now and I need to provide a descent fix.

**Comment by Sciss** [comment]
Ok, so then my suggestion is to merge all but 33649e8aeee0adec05de2572d2b9c57241dbbc92 and 1cd0dd7a9e36e2524a29ef9b77d10d328c2fdfc4 . Can you do that, pick:

- 483b81a091e72a5655d918aa06cf9d7dff76008a
- ec90de133bcb83268461d37a59f6f96d4e43ed7f
- 8cbf58fb9fd64ea52f6789c894057916d479c159
- 6d6aae5bbb381ecfcc8b33c75839a3ecb763a407
- 9ac5e6f27a33b33871c82d211adc2066490381f8
- 9940092c3fc1c259dc14db0a0eb3658e8d3e9dbf

?

**Comment by Sciss** [comment]
I think it would work this way: https://stackoverflow.com/questions/25955822/git-cherry-pick-a-single-commit-for-pull-request - don't know if there is a simpler way.

**Comment by mgarin** [comment]
Pull from the different branch with picked changes sounds good, that would certainly help. Or I can just merge this and simply push some changes on top of it - that might be faster than playing around with git.

**Pull request closed without merging**
