### PR TITLE
Fixed default scroll speed for all WebScrollPane instances (issue #162)

### PR DESCRIPTION
**Pull request by Sorceror**
Fix is based on this discussion http://stackoverflow.com/questions/5583495/how-do-i-speed-up-the-scroll-speed-in-a-jscrollpane-when-using-the-mouse-wheel

### CODE REVIEW

**Comment by mgarin** [comment]
I have included this change into main branch. 
It actually seems to be a good default value for most scroll cases.

**Comment by aeben** [comment]
Hi there, I know this issue is closed, however I've been looking at the JScrollPane code and I tested this fix on WebLaf version 1.26 and it works well (in Linux Mint Mate). In WebScrollPane:
<pre>
    getWebHorizontalScrollBar ().putClientProperty("JScrollBar.fastWheelScrolling",
         Boolean.TRUE);
    getWebVerticalScrollBar ().putClientProperty("JScrollBar.fastWheelScrolling",
         Boolean.TRUE);
</pre>
I don't know if there is any benefit of using this against setUnitIncrement ( 16 ), however that's what the original JScrollPane uses. Just a thought. Thanks for your great work!

**Comment by mgarin** [comment]
Hm, that might indeed be a better solution, didn't notice this option when was porting scrollpane. Thanks for the tip! I will see how does that option works and will probably replace the previous workaround with this one.

**Comment by mgarin** [comment]
I have replaced workaround with these custom properties - those provide a bit faster scrolling and scale better with different scrollable area sizes.

**Pull request merged**
