### PR TITLE
WebCollapsiblePane icons

### PR DESCRIPTION
**Pull request by iMichka**
These changes makes the WebCollapsiblePane use the same icons for the expanded state as the ones defined in the IconSet.

### CODE REVIEW

**Comment by iMichka** [comment]
@mgarin I added the examples as beta, as the component is not cleaned up. Switching between light/dark theme is not working.

I just wanted to the the icons part done, so that they use the same icons as the ones defined in the IconSet.

I am not sure of the disabled icon should be handled, I guess this will be done later using the state mechanism.

**Comment by mgarin** [comment]
Thanks for the changes! 

Everything looks solid except one thing - why did you remove `OrientedIcon`? Even though it might not be used in `WebCollapsiblePane` anymore it is still a separate feature which deserve to exist in the library :)

**Comment by iMichka** [comment]
Right, I removed that commit. It was just that it was not used anymore, so I thought that I could get rid of it :)

**Comment by mgarin** [comment]
Thanks :)
I will check it again and merge tomorrow.

**Pull request merged**
