### PR TITLE
JPopupMenu: use PERPIXEL_TRANSPARENT for heavyweight popups when PERPIXEL_TRANSLUCENT is not available

### PR DESCRIPTION
**Pull request by greg2001**
On Linux, Java per-pixel translucency support is often disabled, depending on the window manager and graphics card driver installed. In this case, WEBLAF reverts to a fully opaque look for both heavy- and lightweight popups.

Heavyweight popup:
2015-04-16 10_39_57-seam09_aps - ufa atprepare

Lightweight popup:
2015-04-16 10_40_17-seam09_aps - ufa atprepare

Kinda uncool, especially the opaque rounded corners...

At the same time, per-pixel transparency (shaped windows) is always supported (tested it with a lot of different Linux versions/configurations). This update makes use of per-pixel transparency for heavyweight popups when per-pixel translucency is not available/disabled.

Heavyweight popup:
2015-04-16 10_44_57-seam09_aps - ufa atprepare

Lightweight popup:
2015-04-16 10_45_20-seam09_aps - ufa atprepare

Much better, imho. The only difference to translucency mode is the absence of the drop shadow and the opacity of heavyweight popups, lightweight popups look the same.

This behavior is disabled by default; to enable, use 

      ProprietaryUtils.setWindowShapeAllowed(true);

To test it under Windows, use

      ProprietaryUtils.setWindowTransparencyAllowed(false);
      ProprietaryUtils.setWindowShapeAllowed(true);

WBR
Gregory

### CODE REVIEW

**Comment by greg2001** [comment]
Also updated WebPopOver to work the same way as JPopupMenu.

Before:
2015-04-17 11_47_46-atprepare - c__gregory_intellij_atprepare - ufashares - z__shares_java_sourc

After:
2015-04-17 11_48_15-atprepare - c__gregory_intellij_atprepare - ufashares - z__shares_java_sourc

**Comment by iMichka** [comment]
Hi

I just gave this a fast try on Ubuntu 12.04 with Xfce. It does fix the opaque edge corners so this is a very nice fix.

One thing which is a little bit odd is that there is a sort of white/grey area popping around the menus (like the one on your WebPopOver example) when they are opened, and then the area disappears. You see it especially if you have a dark background and you move through different menus. It's very fast but still visible.

**Comment by greg2001** [comment]
> It's very fast but still visible.

That's a good point; now, I'm seeing it too :-)))
Will check if there's something that can be tweaked...

**Comment by iMichka** [comment]
Maybe this is the same issue than seen here: https://github.com/mgarin/weblaf/issues/158

**Comment by mgarin** [comment]
This fix might indeed work well on Linux systems, thanks for the changes!

I will take a closer look at the code after releasing some improvements and will merge it in. And probably will also add a few improvements (like properly painting the corner side).

**Comment by mgarin** [comment]
Thanks again for these changes!
I will also include them into the large upcoming chunk of WebLaF modifications.

**Comment by iMichka** [comment]
Just to precise that the strange flicker only happens on the leftmost popup menu.

**Comment by mgarin** [comment]
Thanks to @greg2001 changes it will be fixed in next releases. I have also included some more improvements on top of those changes in `styling` branch and will bring them into `master` later on when it is ready to be released.

**Pull request merged**
